### ISSUE TITLE
Potential Bug in struct_parser.pm: PopMap_for_admixture File Creation Issue

### ISSUE THREAD

**Issue by bwfarm2** [lyl8086/StructureSelector-standalone-version#1]
**Description**
I believe there is a potential issue in the `struct_parser.pm` file, specifically related to creating the `PopMap_for_admixture` file. This issue occurs under certain conditions and may be the root cause of an error when trying to move this file.

**Relevant Code**
The file handler for `PopMap_for_admixture` is created on line 924 of `struct_parser.pm`.
This happens only if the variable `first` is set to 1 (True) and `grp` is undefined.

line 924: 
```
if (!$grp&&$first) {open($out_fh_grp, ">$out_path/PopMap_for_admixture") or die "$!";}
```

Prior to this, on line 895 of `struct_parser.pm`, `grp` is expected to be either the popmap input file or a popmap vector.

line 895-916: 
```
	if ($grp) {
		if ($grp =~ /^(\d+,)*\d+,?$/g) {
			# newpop size.
			my @parts = split(',', $grp);
            my @order;
			my $line = 1;
			for (my $i=0; $i<@parts; $i++) {
				my $size = $parts[$i];
                push @order, $i+1;
                $popsize->{$i+1} = $size;
				$N += $size;
				for (my $j=$line; $j<=$N; $j++) {
					$pops->{$j} = $i+1;
					$line++; # line number.
				}
			}
			$order = \@order;
		} else {
			($pops, $order, $popsize) = parse_popmap($grp);
			$N = scalar(keys %$pops);
		}
	}
```

The `PopMap_for_admixture` file is not created if a popmap input file or popmap vector is provided with the `-p` flag.

However, on line 339 of `structure_selector.pl`, the `PopMap_for_admixture` file is moved.  This results in a failure when the file does not exist.

line 339:
```
    `mv $out_path/PopMap_for_admixture $out_path/${dir}pop.admixlabel`;
```

***Relevant Execution Command***
`structure_selector.pl -i structure_output/ -o /output/file/path/K1-10_output -n run1 -c -p populations_file.txt`

**Comment by lyl8086** [comment]
issue fixed. This file is actually not needed.
